version: 2
jobs:
  install:
    docker:
      - image: circleci/node:carbon
    environment:
      NODE_ENV: not-production
    steps:
      - checkout
      - run:
          name: 'Install dependencies'
          command: 'yarn install'
      - save_cache:
          name: 'Cache node_modules'
          key: node_modules-{{ checksum "yarn.lock" }}
          paths: node_modules
  test:
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - restore_cache:
          name: 'Restore node_modules cache'
          key: node_modules-{{ checksum "yarn.lock" }}
      - run:
          name: 'Run test'
          command: 'yarn run test'

  deploy-to-heroku:
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - run:
          name: 'Setup Heroku'
          command: bash ./scripts/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "19:bb:c1:72:c3:ec:56:33:93:7d:71:f2:9a:5f:da:fa"
      - run:
          name: Deploy Master to Heroku
          command: |
            git push --force git@heroku.com:swift-gateway.git HEAD:refs/heads/master
            heroku run python manage.py deploy --app 'swift-gateway'

workflows:
  version: 2

  test-pr:
    jobs:
      - install:
          filters:
            branches:
              ignore:
                - master
                - develop
      - test:
          requires:
            - install

  deploy:
    jobs:
      - deploy-to-heroku:
          filters:
            branches:
              only:
                - master
